require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'PxViewR' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'PxViewRTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        if target.name == 'RNZipArchive'
          config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
        end
        if config.name == 'Debug'
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        end
      end
      if target.name == 'RNZipArchive'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            file.settings['COMPILER_FLAGS'] = '-DHAVE_INTTYPES_H -DHAVE_PKCRYPT -DHAVE_STDINT_H -DHAVE_WZAES -DHAVE_ZLIB -DMZ_ZIP_NO_SIGNING'
          end
        end
      end
    end
  end
end

target 'PxViewR-tvOS' do
  # Pods for RnDiffApp-tvOS
  target 'PxViewR-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
